# Generated by Django 5.2.4 on 2025-08-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_created_qsets',
        ),
    ]
