# Generated by Django 5.2.4 on 2025-08-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_newsitem'),
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.AddField(
            model_name='notification',
            name='answer_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='diary.answersession', verbose_name='Answer Session'),
        ),
        migrations.AddField(
            model_name='notification',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='diary.questionset', verbose_name='Question Set'),
        ),
    ]
