# Generated by Django 5.2.4 on 2025-08-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notification_link_notification_answer_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Related Object ID'),
        ),
    ]
