# Generated by Django 5.2.4 on 2025-08-28 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
