# Generated by Django 5.2.4 on 2025-08-28 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_weekly_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='next_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
