# Generated by Django 5.2.4 on 2025-08-02 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the question set.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Optional description for this question set.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('owner', models.ForeignKey(help_text='User who created this question set.', on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text of the question.', verbose_name='Question Text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the question in the set.', verbose_name='Order')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diary.questionset', verbose_name='Question Set')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered At')),
                ('respondent', models.ForeignKey(blank=True, help_text='The user who answered these questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Respondent')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sessions', to='diary.questionset', verbose_name='Question Set')),
            ],
            options={
                'verbose_name': 'Answer Session',
                'verbose_name_plural': 'Answer Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text provided as an answer to the question.', verbose_name='Answer Text')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diary.answersession', verbose_name='Answer Session')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diary.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
