# Generated by Django 5.2.4 on 2025-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='style',
            field=models.CharField(choices=[('grunge', 'Grunge'), ('classic', 'Classic'), ('minimal', 'Minimal')], default='classic', max_length=50, verbose_name='Style'),
        ),
    ]
