# Generated by Django 5.2.4 on 2025-08-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_questionset_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSetStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Style Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_name', models.CharField(help_text="e.g. 'style_grunge.html'", max_length=100, verbose_name='Template Filename')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Set Style',
                'verbose_name_plural': 'Question Set Styles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='questionset',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='diary.questionsetstyle', verbose_name='Style'),
        ),
    ]
