# Generated by Django 5.2.4 on 2025-08-06 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_questionsetstyle_alter_questionset_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
