# Generated by Django 5.2.4 on 2025-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_questionset_share_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetstyle',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
