# Generated by Django 5.2.4 on 2025-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_questionsetstyle_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
