# Generated by Django 5.2.4 on 2025-08-13 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_questionset_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline for the news item.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='A brief description or details about the news.', verbose_name='Description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. For example, 1 = first position.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this news item from the homepage.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
