# Generated by Django 5.2.4 on 2025-08-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_text',
            field=models.TextField(default='', help_text='Stores the question text at the time of answering.', verbose_name='Original Question Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='diary.question', verbose_name='Question'),
        ),
    ]
