# Generated by Django 5.2.4 on 2025-08-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_answer_question_text_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersession',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_sessions', to='diary.questionset', verbose_name='Question Set'),
        ),
    ]
